### ISSUE TITLE
Sorting just stopped working when I switched from Merge to Quick

### ISSUE THREAD

**Issue by vidurkhanal** [Sang-it/SortingAlgo#2]
Attached is the image of when it stopped working. To Reproduce the error;
Merge sort an array and quick sort while merge sort is running. 

<img width="1534" alt="Screen Shot 2021-07-07 at 11 59 04 PM" src="https://user-images.githubusercontent.com/65837961/124860306-6bf52280-df7f-11eb-8f13-329cba73ea42.png">

**Comment by Sang-it** [comment]
Your issue has been fixed.
